name: MLOps Pipeline
on:  workflow_dispatch
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACCOUNT_NUMBER: ${{ vars.ACCOUNT_NUMBER }}
  ECR_REPO_NAME: ${{ vars.ECR_REPO_NAME }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  SERVICE_NAME:  ${{ vars.SERVICE_NAME }}
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
  SG_SERVICE: ${{ vars.SG_SERVICE }}
  SUB01:  ${{ vars.SUB01 }}
  SUB02:  ${{ vars.SUB02 }}
  VERSION_TASKDEF: ${{ vars.VERSION_TASKDEF }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
         python-version: ${{ matrix.python-version }}
    - name: Instalar dependencias
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
    - name: Generar Datos
      run: |
         python 01_generar_datos.py
         ls -l quakes.csv
    - name: Ingestar Datos
      run: |
         python 02_ingestar.py
         ls -l test.csv validate.csv train.csv
    - name: Entrenar 
      run: |
         python 03_entrenar.py
         ls -l mlparams
    - name: Probar
      run: |
         python 04_validar.py
    - name: Aprovisionar Repositorio 
      if:  vars.ECR_INICIAR == 'si'
      run: |
        python 05_aprovisionar.py -r
    - name: Aprovisionar  Definicion de tarea ECS
      if:  vars.ECS_TASK_INICIAR == 'si'
      run: |
        python 05_aprovisionar.py -t
    - name: Aprovisionar Servicio ECS
      if:  vars.ECS_SERVICIO_INICIAR == 'si'
      run: |
        python 05_aprovisionar.py -s
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
    - name: Login to Amazon ECR
      uses:  aws-actions/amazon-ecr-login@v1
    - name: Imagen Contendor
      run: |
         docker build . --file Dockerfile --tag  ${{ vars.ECR_REPO_NAME }}:latest
         docker tag ${{ vars.ECR_REPO_NAME }}:latest ${{ vars.ACCOUNT_NUMBER }}.dkr.ecr.${{ vars.AWS_DEFAULT_REGION }}.amazonaws.com/${{ vars.ECR_REPO_NAME }}:latest
         docker push  ${{ vars.ACCOUNT_NUMBER }}.dkr.ecr.${{ vars.AWS_DEFAULT_REGION }}.amazonaws.com/${{ vars.ECR_REPO_NAME }}:latest
